repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        language: system
        entry: pytest
        types: [python]
        pass_filenames: false
